### PR TITLE
FORKED ESPN

### PR DESCRIPTION
**Pull request by cheikhniass74**
In Intelij IDE right click on the project and click run.

### CODE REVIEW

**Comment by jaxzin** [comment]
Did you forget to commit your Java class(es)?

**Comment by cheikhniass74** [comment]
Yea it looks like I did, I am at work right now, but I will add and commit the Java file as soon as I get home, and when I do I will email you to let you know.

Kind Regards, 
Cheikh Niass

**Comment by cheikhniass74** [comment]
The java file is committed.
When using inteliJ right click on the class and click run.

**Comment by cheikhniass74** [comment]
https://github.com/cheikhniass74/fizzbuzz-selenium.git

**Pull request closed without merging**
